// Code generated by protoc-gen-go. DO NOT EDIT.
// source: packet.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// client 內部通知
type PeerConnected struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeerConnected) Reset()         { *m = PeerConnected{} }
func (m *PeerConnected) String() string { return proto.CompactTextString(m) }
func (*PeerConnected) ProtoMessage()    {}
func (*PeerConnected) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9ef1a6541f9f9e7, []int{0}
}

func (m *PeerConnected) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeerConnected.Unmarshal(m, b)
}
func (m *PeerConnected) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeerConnected.Marshal(b, m, deterministic)
}
func (m *PeerConnected) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeerConnected.Merge(m, src)
}
func (m *PeerConnected) XXX_Size() int {
	return xxx_messageInfo_PeerConnected.Size(m)
}
func (m *PeerConnected) XXX_DiscardUnknown() {
	xxx_messageInfo_PeerConnected.DiscardUnknown(m)
}

var xxx_messageInfo_PeerConnected proto.InternalMessageInfo

// 註冊請求.
type RegisterReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Pw                   string   `protobuf:"bytes,2,opt,name=pw,proto3" json:"pw,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterReq) Reset()         { *m = RegisterReq{} }
func (m *RegisterReq) String() string { return proto.CompactTextString(m) }
func (*RegisterReq) ProtoMessage()    {}
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9ef1a6541f9f9e7, []int{1}
}

func (m *RegisterReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterReq.Unmarshal(m, b)
}
func (m *RegisterReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterReq.Marshal(b, m, deterministic)
}
func (m *RegisterReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterReq.Merge(m, src)
}
func (m *RegisterReq) XXX_Size() int {
	return xxx_messageInfo_RegisterReq.Size(m)
}
func (m *RegisterReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterReq.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterReq proto.InternalMessageInfo

func (m *RegisterReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RegisterReq) GetPw() string {
	if m != nil {
		return m.Pw
	}
	return ""
}

// 註冊回應.
type RegisterResp struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResp) Reset()         { *m = RegisterResp{} }
func (m *RegisterResp) String() string { return proto.CompactTextString(m) }
func (*RegisterResp) ProtoMessage()    {}
func (*RegisterResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9ef1a6541f9f9e7, []int{2}
}

func (m *RegisterResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResp.Unmarshal(m, b)
}
func (m *RegisterResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResp.Marshal(b, m, deterministic)
}
func (m *RegisterResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResp.Merge(m, src)
}
func (m *RegisterResp) XXX_Size() int {
	return xxx_messageInfo_RegisterResp.Size(m)
}
func (m *RegisterResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResp.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResp proto.InternalMessageInfo

func (m *RegisterResp) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

//登入請求.
type LoginReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Pw                   string   `protobuf:"bytes,2,opt,name=pw,proto3" json:"pw,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginReq) Reset()         { *m = LoginReq{} }
func (m *LoginReq) String() string { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()    {}
func (*LoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9ef1a6541f9f9e7, []int{3}
}

func (m *LoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReq.Unmarshal(m, b)
}
func (m *LoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReq.Marshal(b, m, deterministic)
}
func (m *LoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReq.Merge(m, src)
}
func (m *LoginReq) XXX_Size() int {
	return xxx_messageInfo_LoginReq.Size(m)
}
func (m *LoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReq proto.InternalMessageInfo

func (m *LoginReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LoginReq) GetPw() string {
	if m != nil {
		return m.Pw
	}
	return ""
}

//登入回應.
type LoginResp struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Token                string   `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	Money                int32    `protobuf:"varint,4,opt,name=money,proto3" json:"money,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResp) Reset()         { *m = LoginResp{} }
func (m *LoginResp) String() string { return proto.CompactTextString(m) }
func (*LoginResp) ProtoMessage()    {}
func (*LoginResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9ef1a6541f9f9e7, []int{4}
}

func (m *LoginResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResp.Unmarshal(m, b)
}
func (m *LoginResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResp.Marshal(b, m, deterministic)
}
func (m *LoginResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResp.Merge(m, src)
}
func (m *LoginResp) XXX_Size() int {
	return xxx_messageInfo_LoginResp.Size(m)
}
func (m *LoginResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResp.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResp proto.InternalMessageInfo

func (m *LoginResp) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func (m *LoginResp) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LoginResp) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *LoginResp) GetMoney() int32 {
	if m != nil {
		return m.Money
	}
	return 0
}

//遊戲-猜拳下注.
type MoraReq struct {
	Index                int32    `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Bet                  int32    `protobuf:"varint,2,opt,name=bet,proto3" json:"bet,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MoraReq) Reset()         { *m = MoraReq{} }
func (m *MoraReq) String() string { return proto.CompactTextString(m) }
func (*MoraReq) ProtoMessage()    {}
func (*MoraReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9ef1a6541f9f9e7, []int{5}
}

func (m *MoraReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MoraReq.Unmarshal(m, b)
}
func (m *MoraReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MoraReq.Marshal(b, m, deterministic)
}
func (m *MoraReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MoraReq.Merge(m, src)
}
func (m *MoraReq) XXX_Size() int {
	return xxx_messageInfo_MoraReq.Size(m)
}
func (m *MoraReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MoraReq.DiscardUnknown(m)
}

var xxx_messageInfo_MoraReq proto.InternalMessageInfo

func (m *MoraReq) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *MoraReq) GetBet() int32 {
	if m != nil {
		return m.Bet
	}
	return 0
}

type MoraResp struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Mora                 int32    `protobuf:"varint,2,opt,name=mora,proto3" json:"mora,omitempty"`
	GameRes              int32    `protobuf:"varint,3,opt,name=gameRes,proto3" json:"gameRes,omitempty"`
	Win                  int32    `protobuf:"varint,4,opt,name=win,proto3" json:"win,omitempty"`
	Draw                 int32    `protobuf:"varint,5,opt,name=draw,proto3" json:"draw,omitempty"`
	Lose                 int32    `protobuf:"varint,6,opt,name=lose,proto3" json:"lose,omitempty"`
	Name                 string   `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	Top                  int32    `protobuf:"varint,8,opt,name=top,proto3" json:"top,omitempty"`
	Money                int32    `protobuf:"varint,9,opt,name=money,proto3" json:"money,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MoraResp) Reset()         { *m = MoraResp{} }
func (m *MoraResp) String() string { return proto.CompactTextString(m) }
func (*MoraResp) ProtoMessage()    {}
func (*MoraResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9ef1a6541f9f9e7, []int{6}
}

func (m *MoraResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MoraResp.Unmarshal(m, b)
}
func (m *MoraResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MoraResp.Marshal(b, m, deterministic)
}
func (m *MoraResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MoraResp.Merge(m, src)
}
func (m *MoraResp) XXX_Size() int {
	return xxx_messageInfo_MoraResp.Size(m)
}
func (m *MoraResp) XXX_DiscardUnknown() {
	xxx_messageInfo_MoraResp.DiscardUnknown(m)
}

var xxx_messageInfo_MoraResp proto.InternalMessageInfo

func (m *MoraResp) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func (m *MoraResp) GetMora() int32 {
	if m != nil {
		return m.Mora
	}
	return 0
}

func (m *MoraResp) GetGameRes() int32 {
	if m != nil {
		return m.GameRes
	}
	return 0
}

func (m *MoraResp) GetWin() int32 {
	if m != nil {
		return m.Win
	}
	return 0
}

func (m *MoraResp) GetDraw() int32 {
	if m != nil {
		return m.Draw
	}
	return 0
}

func (m *MoraResp) GetLose() int32 {
	if m != nil {
		return m.Lose
	}
	return 0
}

func (m *MoraResp) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MoraResp) GetTop() int32 {
	if m != nil {
		return m.Top
	}
	return 0
}

func (m *MoraResp) GetMoney() int32 {
	if m != nil {
		return m.Money
	}
	return 0
}

func init() {
	proto.RegisterType((*PeerConnected)(nil), "proto.PeerConnected")
	proto.RegisterType((*RegisterReq)(nil), "proto.RegisterReq")
	proto.RegisterType((*RegisterResp)(nil), "proto.RegisterResp")
	proto.RegisterType((*LoginReq)(nil), "proto.LoginReq")
	proto.RegisterType((*LoginResp)(nil), "proto.LoginResp")
	proto.RegisterType((*MoraReq)(nil), "proto.MoraReq")
	proto.RegisterType((*MoraResp)(nil), "proto.MoraResp")
}

func init() { proto.RegisterFile("packet.proto", fileDescriptor_e9ef1a6541f9f9e7) }

var fileDescriptor_e9ef1a6541f9f9e7 = []byte{
	// 285 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0x4d, 0x6a, 0xf3, 0x30,
	0x14, 0x24, 0x4e, 0xe4, 0x9f, 0xf7, 0xe5, 0x6b, 0x83, 0x08, 0x45, 0xcb, 0xa2, 0x45, 0xe9, 0x2a,
	0x10, 0x7a, 0x84, 0x6e, 0x5b, 0x28, 0xba, 0x81, 0x62, 0x3f, 0x8c, 0x49, 0xac, 0xa7, 0xca, 0x2a,
	0x6e, 0x2f, 0xd8, 0x73, 0x15, 0x49, 0x6e, 0xe2, 0x4d, 0x4b, 0x57, 0x9e, 0x19, 0x3c, 0xf3, 0x66,
	0x40, 0xb0, 0xb6, 0xba, 0x3e, 0xa2, 0xdf, 0x59, 0x47, 0x9e, 0x38, 0x8b, 0x1f, 0x79, 0x0d, 0xff,
	0x5f, 0x10, 0xdd, 0x23, 0x19, 0x83, 0xb5, 0xc7, 0x46, 0xee, 0xe1, 0x9f, 0xc2, 0xb6, 0x1b, 0x3c,
	0x3a, 0x85, 0xaf, 0x9c, 0xc3, 0xca, 0xe8, 0x1e, 0xc5, 0xe2, 0x76, 0x71, 0x5f, 0xa9, 0x88, 0xf9,
	0x15, 0x64, 0x76, 0x14, 0x59, 0x54, 0x32, 0x3b, 0xca, 0x3b, 0x58, 0x5f, 0x2c, 0x83, 0xe5, 0x37,
	0x90, 0x3b, 0x1c, 0xde, 0x4e, 0x3e, 0xba, 0x98, 0x9a, 0x98, 0xdc, 0x41, 0xf9, 0x44, 0x6d, 0x67,
	0xfe, 0x9a, 0x5b, 0x43, 0x35, 0xfd, 0xff, 0x73, 0xe8, 0x39, 0x28, 0x9b, 0x05, 0x6d, 0x81, 0x79,
	0x3a, 0xa2, 0x11, 0xcb, 0x28, 0x26, 0x12, 0xd4, 0x9e, 0x0c, 0x7e, 0x88, 0x55, 0x0c, 0x48, 0x44,
	0xee, 0xa1, 0x78, 0x26, 0xa7, 0x43, 0xa7, 0x2d, 0xb0, 0xce, 0x34, 0xf8, 0x3e, 0x5d, 0x48, 0x84,
	0x6f, 0x60, 0x79, 0x40, 0x1f, 0xf3, 0x99, 0x0a, 0x50, 0x7e, 0x2e, 0xa0, 0x4c, 0x9e, 0xdf, 0x7b,
	0xf5, 0xe4, 0xf4, 0xe4, 0x8b, 0x98, 0x0b, 0x28, 0x5a, 0xdd, 0xa3, 0xc2, 0x21, 0x36, 0x63, 0xea,
	0x9b, 0x86, 0x23, 0x63, 0x67, 0xa6, 0x66, 0x01, 0x06, 0x7f, 0xe3, 0xf4, 0x28, 0x58, 0xf2, 0x07,
	0x1c, 0xb4, 0x13, 0x0d, 0x28, 0xf2, 0xa4, 0x05, 0x7c, 0xde, 0x5f, 0xcc, 0xf6, 0x6f, 0x60, 0xe9,
	0xc9, 0x8a, 0x32, 0xa5, 0x79, 0xb2, 0x97, 0xed, 0xd5, 0x6c, 0xfb, 0x21, 0x8f, 0x6f, 0xe0, 0xe1,
	0x2b, 0x00, 0x00, 0xff, 0xff, 0x5e, 0x40, 0x10, 0x60, 0x1a, 0x02, 0x00, 0x00,
}
